### ISSUE TITLE
Starter code

### ISSUE THREAD

**Issue by VarunDevPro** [UdacityMobileWebScholarship/guess-quote#6]
There's a large amount of starter code, what do you think about it. I would like to have very less code, since many members may not know react. I want that this project should enable everyone to contribute, more or less. 

## Issue 1:
My idea 💡 is to re-commit the starter code with lesser code.  
**If you have took any course before, you may know that instructors start from scratch, then react, then react-router, then redux, then any backend like firebase.**  
But we now have everything together 

## Issue 2:
Is there any chance to seperate server and client code. It would be easy for all the developers who only know either front or backend, not both.  
**Also deployment would be easy, if it's possible**

## Issue 3:
Create readmes in almost every folder, it would be easier for non-js (php,django,etc.,)developers. And also create map(s) for contributions, where to start and how the execution goes to render the page.

**Being a contributor and collaborator, these are my suggestions for this project, I thought this would be more appropriate place than the slack channel**

Your feedback is highly important and appreciated (will be accounted too)...

**Comment by sounak07** [comment]
Yes, I agree, starter code should be as less as possible as that would help us understand it way better.

**Comment by twishasaraiya** [comment]
@VarunDevPro, I completely understand your concern that you want to make it easy for contributors to be able to contribute to the project. Lot of starter code may seem confusing for new contributors atfirst but I think with proper guidelines we can solve that.

**Issue 1**
Since our project code is anyways gonna grow with time I think instead of recommitting the starter code we should instead provide with a better documentation(just as you said in Issue 3) so that it becomes easier for everyone to navigate the code. My idea 💡is we could develop Wiki Pages for client and server side.

**Issue 2**
By separate server and client code, I think you mean separate repositories because we have definitely separated server and client code in separate folder.

**Issue 3:**
I agree with you that we should develop a guide so that becomes easier for different types of contributors to start contributing. But instead of README files in every folder, I suggest we use GitHub Wiki pages. We can have README for the 2 main (client and server) folder but for every folder it seems too much.

**Comment by skyshader** [comment]
So our idea was to have a starter code which is already well defined.

The idea is to explain the flow of the app in the readme and once we do that, trust me it will be very helpful for people to follow along.

Consider the current code base. What contributors are going to contribute about when all the configuration part is done? Follow the path and create feature in the similar flow.

Our main goal with this was to make things easier which I understand is not because of lack of documentation (that's our first priority and it's just a basic flow and explanation about what belongs where) and to have contributors adhere to the flow in which we want them to write the code.

Let me know your thoughts? :)

**Comment by VarunDevPro** [comment]
Ok @twishasaraiya  has addressed all the issues, so we can close this now
